name: 简体化备份脚本

on:
  push:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: 更新代码
        uses: actions/checkout@v3
      - name: 安装环境
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt
      - name: 拉取脚本
        run: |
          git clone https://github.com/YAWAsau/backup_script.git
          rm -rf backup_script/DCIM
          rm -rf backup_script/.git
      - name: 开始转换
        run: |
          python3 convert.py
      - name: 打包
        run: |
          zip -r backup_script.zip backup_script
          ls
      - name: 发布
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            backup_script.zip