name: 简体化备份脚本

on:
  push:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: 更新代码
        uses: actions/checkout@v3
      - name: 安装环境
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt
      - name: 拉取脚本
        run: |
          git clone https://github.com/YAWAsau/backup_script.git
      - name: 开始转换
        run: |
          python3 convert.py
      - name: 打包
        run: |
          zip -r backup_script.zip backup_script
          ls
      - name: 发布
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PRIVATE_KEY }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
      - name: 上传附件
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: backup_script.zip
          asset_name: backup_script.zip
          asset_content_type: application/zip
