name: 简体化备份脚本

on:
  push:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: 更新代码
        uses: actions/checkout@v2
      - name: 安装环境
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt
      - name: 拉取脚本
        run: |
          git clone https://github.com/YAWAsau/backup_script.git
          mv backup_script speed-backup
          cd speed-backup
          ls
      - name: 开始转换
        run: |
          python3 convert.py
